---
galaxy_info:
  author: GoodLabs Studio
  description: Mints and manages the self-signed Kafka root CA.
  license: Proprietary
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions: ["8", "9"]
    - name: Ubuntu
      versions: ["20.04", "22.04"]
dependencies: []
